### ISSUE TITLE
Crash on startup up due to Forge CIT

### ISSUE THREAD

**Issue by ReeCodes** [Tfarcenim/CIT-Reforged#4] opened 2023-11-03 14:38 UTC
[crash-2023-11-03_15.37.13-client.txt](https://github.com/Tfarcenim/CIT-Reforged/files/13251400/crash-2023-11-03_15.37.13-client.txt)

**Comment by Tfarcenim** [comment] 2023-11-03 17:32
Send full log and test with Forge 47.1.3 as this mod does not support any higher.

**Comment by ReeCodes** [comment] 2023-11-06 15:16
What's the big deal with going up one Forge version?

**Comment by Tfarcenim** [comment] 2023-11-06 21:23
Forge/Neoforge split happened so mods made for newer than 47.1.3 require one or the other.  I won't stop you from running newer forge versions, but I also won't help with any bugs/crashes caused by newer versions either.

**Comment by Tfarcenim** [comment] 2023-11-06 21:25
So do you have the latest.log/debug.log or not?  I suspect that is a red herring crash caused by an earlier failure in the loading cycle, usually missing dependencies.

**Comment by ReeCodes** [comment] 2023-11-14 18:22
latest.log:
https://mclo.gs/HCjxpTz

**Comment by Tfarcenim** [comment] 2023-11-15 05:58
The crash has nothing to do with Forge CIT, always check the full log before reporting
> 26 | Mod ID: 'forge', Requested by: 'carryon', Expected range: '[46,47.1.3]', Actual version: '47.2.6'

If it's still crashing after fixing, upload a new log (only reason I'm not closing this issue yet)

**Comment by ReeCodes** [comment] 2023-11-18 08:20
"Caused by: java.lang.NullPointerException: Cannot read field "activeCITs" because "shcm.shsupercm.forge.citresewn.CITResewn.INSTANCE" is null"

**Comment by Tfarcenim** [comment] 2023-11-19 05:02
So it's another mod failing, but blaming this one because this crash isn't possible otherwise, closed.

**Closed as completed by Tfarcenim** 2023-11-19 05:02 UTC
Labels: bug, wontfix, bug in other software
